title: Peacewater
short_title: Peacewater Database
description: Peacewater database a project of Peace Engineering and Sustainable Community Development Hub
baseurl:
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
  project:
    output: true
    permalink: "/project/:path/"
  topics:
    output: true
    permalink: "/topic/:path/"    
  contexts:
    output: true
    permalink: "/context/:path/"    
  reports:
    output: true
    permalink: "/report/:path/"    



# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
plugins:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
